define(function(require){
	var app = require('../app');
	app.config(['$stateProvider','$urlRouterProvider',function($stateProvider,$urlRouterProvider) {
		$urlRouterProvider.otherwise('/login');
		$stateProvider
				.state('login',{
					url:'/login',
					views:{
						'':{
							templateUrl:'views/login/login.html',
							controllerUrl:'views/login/login',
							controller:'loginCrl'
						}
					}
				})
				.state('main',{
					url:'/main',
					abstract:true,
					views:{
						'':{
							templateUrl:'views/main/main.html',
	  						controllerUrl:'views/main/main',
	  						controller:'mainCrl'
						}
					}
				})
				//基础信息
		  		.state('main.baseInfo',{
		  			url:'/baseInfo',
		  			views:{
		  				'top@main':{
	  						templateUrl:'views/main/top/top.html',
	  						controllerUrl:'views/main/top/top',
	  						controller:'topCrl'
		  				},
		  				'left@main':{
	  						templateUrl:'views/main/left/left.html',
	  						controllerUrl:'views/main/left/left',
	  						controller:'leftCrl'
		  				},
		  				//黑名单
		  				'main@main':{
  							templateUrl:'views/main/baseInfo/baseInfo.html',
				  			controllerUrl:'views/main/baseInfo/baseInfo',
				  			controller:'baseInfoCrl'
		  				}
		  			}
		  		})
		  		
	}]);
});